brew 'git'
brew 'peco'
brew 'zsh-completions'
brew 'zsh'

cask 'google-chrome'
cask 'iterm2'
cask 'visual-studio-code'

# brew 'anyenv'
# brew 'asdf'
# brew 'direnv'
# brew 'kube-ps1'
# brew 'kubectl'
# brew 'kubectx'

# cask '1password'
# cask 'atom'
# cask 'burp-suite'
# cask 'docker'
# cask 'dropbox'
# cask 'evernote'
# cask 'firefox'
# cask 'google-cloud-sdk'
# cask 'minikube'
# cask 'slack'
# cask 'sourcetree'
# cask 'sublime-text'
# cask 'wireshark'
# cask 'zoom'
