brew 'git'
brew 'peco'
brew 'zsh-completions'
brew 'zsh'

cask 'google-chrome'
cask 'iterm2'
cask 'slack'
cask 'visual-studio-code'

# brew 'actionlint'
# brew 'anyenv'
# brew 'argocd'
# brew 'asdf'
# brew 'awscli'
# brew 'azure-cli'
# brew 'bazelisk'
# brew 'direnv'
# brew 'envoy'
# brew 'gh'
# brew 'git-lfs'
# brew 'go'
# brew 'graphviz'
# brew 'hadolint'
# brew 'ibazel'
# brew 'jq'
# brew 'k3d'
# brew 'k6'
# brew 'kube-ps1'
# brew 'kubeconform'
# brew 'kubectl'
# brew 'kubectx'
# brew 'mise'
# brew 'nkf'
# brew 'rustup-init'
# brew 'shellcheck'
# brew 'sops'
# brew 'terragrunt'
# brew 'tree'
# brew 'wget'
# brew 'yq'

# brew 'derailed/k9s/k9s'
# brew 'hashicorp/tap/terraform'
# brew 'kayac/tap/ecspresso'

# cask '1password'
# cask 'android-studio'
# cask 'bettertouchtool'
# cask 'burp-suite'
# cask 'discord'
# cask 'docker'
# cask 'evernote'
# cask 'figma'
# cask 'firefox'
# cask 'google-cloud-sdk'
# cask 'minikube'
# cask 'postman'
# cask 'snowflake-snowsql'
# cask 'sourcetree'
# cask 'spotify'
# cask 'wireshark'
# cask 'zoom'
